# Stage 1: Building the code
FROM node:18.17.0-alpine as builder

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . ./

# No need to run npm run build for development mode

# Stage 2: Run the development code
FROM node:18.17.0-alpine

WORKDIR /app
COPY --from=builder /app/next.config.js ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 3000
CMD ["npm", "run", "dev"]
