// // src/app/layout.tsx

// import React from 'react';
// import { Metadata } from 'next';
// import Link from 'next/link';
// import { Inter } from 'next/font/google';
// import './globals.css';
// import { AuthProvider } from '../utils/AuthProvider';

// const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <AuthProvider> {/* Wrap your application with AuthProvider */}
//       <html lang="en">
//         <body className={inter.className}>
//           <div>
//             <h1>Welcome to the Inflation Game</h1>
//             <p>This is the landing page for your Inflation Management Game.</p>
//             <div>
//               <Link href="/login">Login</Link>
//             </div>
//             <div>
//               <Link href="/register">Register</Link>
//             </div>
//           </div>
//           {children} {/* Render the child components */}
//         </body>
//       </html>
//     </AuthProvider>
//   );
// }
// pages/index.tsx
import React from 'react';
import Link from 'next/link';

const HomePage: React.FC = () => {
  return (
    <div>
      <h1>Home</h1>
      <p>Welcome to our application...</p>
      <Link href="/login">
        Log in
      </Link>
      <Link href="/register">
        Register
      </Link>
    </div>
  );
};

export default HomePage;
